# 上位トピック数と下位トピック数を設定します.
# 一度に複数のトピック数の組み合わででプログラムを実行できます.
# (上位トピック数, 下位トピック数) のリストを topics に入れてください.
# 以下の場合は, (上位トピック数, 下位トピック数) = (2, 30) と (3, 50) でそれぞれ実行され明日.
topics:
    -
        - 2
        - 3
    -
        - 3
        - 5
# Gibbs サンプリングでのイテレーション数を設定します. この数が大きいほど実行時間がかかります.
# 十分な精度を得るためには5000~10000ほどの値が推奨されます.
num_iterations: 10000

# 使用するデータセットを指定してください.
# (詳しくは doc/data.md を参照してください)
# 以下の場合は, ディレクトリ data/sample にある data.txt と genes.txt が使用されます.
dataset: 'sample'

# 結果を出力するディレクトリと, 各出力ファイルのファイル名を指定してください.
# (注) 絶対パスで指定してください.
output_dir: '/tmp'

# 以下は Advanced settings です.

# jar ファイルの場所をデフォルトから変更する場合は設定してください.
jar: './genePAM.jar'

# 使用メモリを制限する場合は以下に最大使用容量(単位: GB)入力してください. デフォルトは-1 (制限無し) です.
mem_limit: -1
